/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.ui.tests;

import com.google.inject.Injector;
import fr.istic.idm.grammar.ui.internal.GrammarActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SwagUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GrammarActivator.getInstance().getInjector("fr.istic.idm.Swag");
	}

}
