/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.istic.idm.SwagRuntimeModule;
import fr.istic.idm.SwagStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SwagIdeSetup extends SwagStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SwagRuntimeModule(), new SwagIdeModule()));
	}
	
}
