/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SwagUiModule extends AbstractSwagUiModule {

	public SwagUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
