/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.ArrayNode#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getArrayNode()
 * @model
 * @generated
 */
public interface ArrayNode extends Node
{
  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(ListFilter)
   * @see fr.istic.idm.swag.SwagPackage#getArrayNode_Filter()
   * @model containment="true"
   * @generated
   */
  ListFilter getFilter();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.ArrayNode#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(ListFilter value);

} // ArrayNode
