/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.swag.SwagPackage#getBasicNode()
 * @model
 * @generated
 */
public interface BasicNode extends Node
{
} // BasicNode
