/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bound Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.BoundFilter#getMin <em>Min</em>}</li>
 *   <li>{@link fr.istic.idm.swag.BoundFilter#getMax <em>Max</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getBoundFilter()
 * @model
 * @generated
 */
public interface BoundFilter extends Filter
{
  /**
   * Returns the value of the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min</em>' attribute.
   * @see #setMin(int)
   * @see fr.istic.idm.swag.SwagPackage#getBoundFilter_Min()
   * @model
   * @generated
   */
  int getMin();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.BoundFilter#getMin <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min</em>' attribute.
   * @see #getMin()
   * @generated
   */
  void setMin(int value);

  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(int)
   * @see fr.istic.idm.swag.SwagPackage#getBoundFilter_Max()
   * @model
   * @generated
   */
  int getMax();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.BoundFilter#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(int value);

} // BoundFilter
