/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equal Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.EqualFilter#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getEqualFilter()
 * @model
 * @generated
 */
public interface EqualFilter extends PathFilter
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(JsonValue)
   * @see fr.istic.idm.swag.SwagPackage#getEqualFilter_Value()
   * @model containment="true"
   * @generated
   */
  JsonValue getValue();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.EqualFilter#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(JsonValue value);

} // EqualFilter
