/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exist Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.swag.SwagPackage#getExistFilter()
 * @model
 * @generated
 */
public interface ExistFilter extends PathFilter
{
} // ExistFilter
