/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Index Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.IndexFilter#getIndex <em>Index</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getIndexFilter()
 * @model
 * @generated
 */
public interface IndexFilter extends Filter
{
  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(int)
   * @see fr.istic.idm.swag.SwagPackage#getIndexFilter_Index()
   * @model
   * @generated
   */
  int getIndex();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.IndexFilter#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(int value);

} // IndexFilter
