/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Null</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.swag.SwagPackage#getJsonNull()
 * @model
 * @generated
 */
public interface JsonNull extends JsonValue
{
} // JsonNull
