/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.JsonBoolean#getBool <em>Bool</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getJsonBoolean()
 * @model
 * @generated
 */
public interface JsonBoolean extends JsonValue
{
  /**
   * Returns the value of the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' attribute.
   * @see #setBool(String)
   * @see fr.istic.idm.swag.SwagPackage#getJsonBoolean_Bool()
   * @model
   * @generated
   */
  String getBool();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.JsonBoolean#getBool <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' attribute.
   * @see #getBool()
   * @generated
   */
  void setBool(String value);

} // JsonBoolean
