/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.JsonNumber#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getJsonNumber()
 * @model
 * @generated
 */
public interface JsonNumber extends JsonValue
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(String)
   * @see fr.istic.idm.swag.SwagPackage#getJsonNumber_Number()
   * @model
   * @generated
   */
  String getNumber();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.JsonNumber#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(String value);

} // JsonNumber
