/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.ListFilter#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getListFilter()
 * @model
 * @generated
 */
public interface ListFilter extends EObject
{
  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.swag.Filter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference list.
   * @see fr.istic.idm.swag.SwagPackage#getListFilter_Filter()
   * @model containment="true"
   * @generated
   */
  EList<Filter> getFilter();

} // ListFilter
