/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.Node#getStr <em>Str</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' attribute.
   * @see #setStr(String)
   * @see fr.istic.idm.swag.SwagPackage#getNode_Str()
   * @model
   * @generated
   */
  String getStr();

  /**
   * Sets the value of the '{@link fr.istic.idm.swag.Node#getStr <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' attribute.
   * @see #getStr()
   * @generated
   */
  void setStr(String value);

} // Node
