/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.swag.Path#getNode <em>Node</em>}</li>
 *   <li>{@link fr.istic.idm.swag.Path#getNodes <em>Nodes</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.swag.SwagPackage#getPath()
 * @model
 * @generated
 */
public interface Path extends EObject
{
  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.swag.Node}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference list.
   * @see fr.istic.idm.swag.SwagPackage#getPath_Node()
   * @model containment="true"
   * @generated
   */
  EList<Node> getNode();

  /**
   * Returns the value of the '<em><b>Nodes</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.swag.Node}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' containment reference list.
   * @see fr.istic.idm.swag.SwagPackage#getPath_Nodes()
   * @model containment="true"
   * @generated
   */
  EList<Node> getNodes();

} // Path
