/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.swag.SwagPackage#getPath()
 * @model
 * @generated
 */
public interface Path extends EObject
{
} // Path
