/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Root Path</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.swag.SwagPackage#getRootPath()
 * @model
 * @generated
 */
public interface RootPath extends Path
{
} // RootPath
