/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.istic.idm.swag.SwagPackage
 * @generated
 */
public interface SwagFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SwagFactory eINSTANCE = fr.istic.idm.swag.impl.SwagFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Path</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path</em>'.
   * @generated
   */
  Path createPath();

  /**
   * Returns a new object of class '<em>Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Node</em>'.
   * @generated
   */
  Node createNode();

  /**
   * Returns a new object of class '<em>Basic Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basic Node</em>'.
   * @generated
   */
  BasicNode createBasicNode();

  /**
   * Returns a new object of class '<em>Array Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Array Node</em>'.
   * @generated
   */
  ArrayNode createArrayNode();

  /**
   * Returns a new object of class '<em>Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter</em>'.
   * @generated
   */
  Filter createFilter();

  /**
   * Returns a new object of class '<em>All Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Filter</em>'.
   * @generated
   */
  AllFilter createAllFilter();

  /**
   * Returns a new object of class '<em>Path Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path Filter</em>'.
   * @generated
   */
  PathFilter createPathFilter();

  /**
   * Returns a new object of class '<em>Equal Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equal Filter</em>'.
   * @generated
   */
  EqualFilter createEqualFilter();

  /**
   * Returns a new object of class '<em>Exist Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exist Filter</em>'.
   * @generated
   */
  ExistFilter createExistFilter();

  /**
   * Returns a new object of class '<em>Bound Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Filter</em>'.
   * @generated
   */
  BoundFilter createBoundFilter();

  /**
   * Returns a new object of class '<em>List Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Filter</em>'.
   * @generated
   */
  ListFilter createListFilter();

  /**
   * Returns a new object of class '<em>Nullable Int</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nullable Int</em>'.
   * @generated
   */
  NullableInt createNullableInt();

  /**
   * Returns a new object of class '<em>Json Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Value</em>'.
   * @generated
   */
  JsonValue createJsonValue();

  /**
   * Returns a new object of class '<em>Json Null</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Null</em>'.
   * @generated
   */
  JsonNull createJsonNull();

  /**
   * Returns a new object of class '<em>Json Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Number</em>'.
   * @generated
   */
  JsonNumber createJsonNumber();

  /**
   * Returns a new object of class '<em>Json Boolean</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Boolean</em>'.
   * @generated
   */
  JsonBoolean createJsonBoolean();

  /**
   * Returns a new object of class '<em>Json String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json String</em>'.
   * @generated
   */
  JsonString createJsonString();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SwagPackage getSwagPackage();

} //SwagFactory
