/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.istic.idm.swag.SwagFactory
 * @model kind="package"
 * @generated
 */
public interface SwagPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "swag";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.istic.fr/idm/Swag";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "swag";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SwagPackage eINSTANCE = fr.istic.idm.swag.impl.SwagPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.PathImpl <em>Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.PathImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getPath()
   * @generated
   */
  int PATH = 0;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH__NODES = 0;

  /**
   * The number of structural features of the '<em>Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.NodeImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getNode()
   * @generated
   */
  int NODE = 1;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__STR = 0;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.BasicNodeImpl <em>Basic Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.BasicNodeImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getBasicNode()
   * @generated
   */
  int BASIC_NODE = 2;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_NODE__STR = NODE__STR;

  /**
   * The number of structural features of the '<em>Basic Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.ArrayNodeImpl <em>Array Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.ArrayNodeImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getArrayNode()
   * @generated
   */
  int ARRAY_NODE = 3;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_NODE__STR = NODE__STR;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_NODE__FILTER = NODE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Array Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_NODE_FEATURE_COUNT = NODE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.FilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 4;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.AllFilterImpl <em>All Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.AllFilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getAllFilter()
   * @generated
   */
  int ALL_FILTER = 5;

  /**
   * The number of structural features of the '<em>All Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.PathFilterImpl <em>Path Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.PathFilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getPathFilter()
   * @generated
   */
  int PATH_FILTER = 6;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FILTER__PATH = FILTER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Path Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.EqualFilterImpl <em>Equal Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.EqualFilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getEqualFilter()
   * @generated
   */
  int EQUAL_FILTER = 7;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FILTER__PATH = PATH_FILTER__PATH;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FILTER__VALUE = PATH_FILTER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Equal Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FILTER_FEATURE_COUNT = PATH_FILTER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.ExistFilterImpl <em>Exist Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.ExistFilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getExistFilter()
   * @generated
   */
  int EXIST_FILTER = 8;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIST_FILTER__PATH = PATH_FILTER__PATH;

  /**
   * The number of structural features of the '<em>Exist Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIST_FILTER_FEATURE_COUNT = PATH_FILTER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.IndexFilterImpl <em>Index Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.IndexFilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getIndexFilter()
   * @generated
   */
  int INDEX_FILTER = 9;

  /**
   * The feature id for the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDEX_FILTER__INDEX = FILTER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Index Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDEX_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.BoundFilterImpl <em>Bound Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.BoundFilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getBoundFilter()
   * @generated
   */
  int BOUND_FILTER = 10;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUND_FILTER__MIN = FILTER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUND_FILTER__MAX = FILTER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bound Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOUND_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.ListFilterImpl <em>List Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.ListFilterImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getListFilter()
   * @generated
   */
  int LIST_FILTER = 11;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FILTER__FILTER = 0;

  /**
   * The number of structural features of the '<em>List Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FILTER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.JsonValueImpl <em>Json Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.JsonValueImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonValue()
   * @generated
   */
  int JSON_VALUE = 12;

  /**
   * The number of structural features of the '<em>Json Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.JsonNullImpl <em>Json Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.JsonNullImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonNull()
   * @generated
   */
  int JSON_NULL = 13;

  /**
   * The number of structural features of the '<em>Json Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NULL_FEATURE_COUNT = JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.JsonNumberImpl <em>Json Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.JsonNumberImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonNumber()
   * @generated
   */
  int JSON_NUMBER = 14;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER__NUMBER = JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_NUMBER_FEATURE_COUNT = JSON_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.JsonBooleanImpl <em>Json Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.JsonBooleanImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonBoolean()
   * @generated
   */
  int JSON_BOOLEAN = 15;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN__BOOL = JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN_FEATURE_COUNT = JSON_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.istic.idm.swag.impl.JsonStringImpl <em>Json String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.istic.idm.swag.impl.JsonStringImpl
   * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonString()
   * @generated
   */
  int JSON_STRING = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING__VALUE = JSON_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING_FEATURE_COUNT = JSON_VALUE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.Path <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path</em>'.
   * @see fr.istic.idm.swag.Path
   * @generated
   */
  EClass getPath();

  /**
   * Returns the meta object for the containment reference list '{@link fr.istic.idm.swag.Path#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see fr.istic.idm.swag.Path#getNodes()
   * @see #getPath()
   * @generated
   */
  EReference getPath_Nodes();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see fr.istic.idm.swag.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link fr.istic.idm.swag.Node#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see fr.istic.idm.swag.Node#getStr()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Str();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.BasicNode <em>Basic Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Basic Node</em>'.
   * @see fr.istic.idm.swag.BasicNode
   * @generated
   */
  EClass getBasicNode();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.ArrayNode <em>Array Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Node</em>'.
   * @see fr.istic.idm.swag.ArrayNode
   * @generated
   */
  EClass getArrayNode();

  /**
   * Returns the meta object for the containment reference '{@link fr.istic.idm.swag.ArrayNode#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see fr.istic.idm.swag.ArrayNode#getFilter()
   * @see #getArrayNode()
   * @generated
   */
  EReference getArrayNode_Filter();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see fr.istic.idm.swag.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.AllFilter <em>All Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Filter</em>'.
   * @see fr.istic.idm.swag.AllFilter
   * @generated
   */
  EClass getAllFilter();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.PathFilter <em>Path Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Filter</em>'.
   * @see fr.istic.idm.swag.PathFilter
   * @generated
   */
  EClass getPathFilter();

  /**
   * Returns the meta object for the containment reference '{@link fr.istic.idm.swag.PathFilter#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see fr.istic.idm.swag.PathFilter#getPath()
   * @see #getPathFilter()
   * @generated
   */
  EReference getPathFilter_Path();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.EqualFilter <em>Equal Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal Filter</em>'.
   * @see fr.istic.idm.swag.EqualFilter
   * @generated
   */
  EClass getEqualFilter();

  /**
   * Returns the meta object for the containment reference '{@link fr.istic.idm.swag.EqualFilter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.istic.idm.swag.EqualFilter#getValue()
   * @see #getEqualFilter()
   * @generated
   */
  EReference getEqualFilter_Value();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.ExistFilter <em>Exist Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exist Filter</em>'.
   * @see fr.istic.idm.swag.ExistFilter
   * @generated
   */
  EClass getExistFilter();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.IndexFilter <em>Index Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Index Filter</em>'.
   * @see fr.istic.idm.swag.IndexFilter
   * @generated
   */
  EClass getIndexFilter();

  /**
   * Returns the meta object for the attribute '{@link fr.istic.idm.swag.IndexFilter#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Index</em>'.
   * @see fr.istic.idm.swag.IndexFilter#getIndex()
   * @see #getIndexFilter()
   * @generated
   */
  EAttribute getIndexFilter_Index();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.BoundFilter <em>Bound Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bound Filter</em>'.
   * @see fr.istic.idm.swag.BoundFilter
   * @generated
   */
  EClass getBoundFilter();

  /**
   * Returns the meta object for the attribute '{@link fr.istic.idm.swag.BoundFilter#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see fr.istic.idm.swag.BoundFilter#getMin()
   * @see #getBoundFilter()
   * @generated
   */
  EAttribute getBoundFilter_Min();

  /**
   * Returns the meta object for the attribute '{@link fr.istic.idm.swag.BoundFilter#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see fr.istic.idm.swag.BoundFilter#getMax()
   * @see #getBoundFilter()
   * @generated
   */
  EAttribute getBoundFilter_Max();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.ListFilter <em>List Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Filter</em>'.
   * @see fr.istic.idm.swag.ListFilter
   * @generated
   */
  EClass getListFilter();

  /**
   * Returns the meta object for the containment reference list '{@link fr.istic.idm.swag.ListFilter#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Filter</em>'.
   * @see fr.istic.idm.swag.ListFilter#getFilter()
   * @see #getListFilter()
   * @generated
   */
  EReference getListFilter_Filter();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.JsonValue <em>Json Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Value</em>'.
   * @see fr.istic.idm.swag.JsonValue
   * @generated
   */
  EClass getJsonValue();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.JsonNull <em>Json Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Null</em>'.
   * @see fr.istic.idm.swag.JsonNull
   * @generated
   */
  EClass getJsonNull();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.JsonNumber <em>Json Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Number</em>'.
   * @see fr.istic.idm.swag.JsonNumber
   * @generated
   */
  EClass getJsonNumber();

  /**
   * Returns the meta object for the attribute '{@link fr.istic.idm.swag.JsonNumber#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see fr.istic.idm.swag.JsonNumber#getNumber()
   * @see #getJsonNumber()
   * @generated
   */
  EAttribute getJsonNumber_Number();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.JsonBoolean <em>Json Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Boolean</em>'.
   * @see fr.istic.idm.swag.JsonBoolean
   * @generated
   */
  EClass getJsonBoolean();

  /**
   * Returns the meta object for the attribute '{@link fr.istic.idm.swag.JsonBoolean#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see fr.istic.idm.swag.JsonBoolean#getBool()
   * @see #getJsonBoolean()
   * @generated
   */
  EAttribute getJsonBoolean_Bool();

  /**
   * Returns the meta object for class '{@link fr.istic.idm.swag.JsonString <em>Json String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json String</em>'.
   * @see fr.istic.idm.swag.JsonString
   * @generated
   */
  EClass getJsonString();

  /**
   * Returns the meta object for the attribute '{@link fr.istic.idm.swag.JsonString#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.istic.idm.swag.JsonString#getValue()
   * @see #getJsonString()
   * @generated
   */
  EAttribute getJsonString_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SwagFactory getSwagFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.PathImpl <em>Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.PathImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getPath()
     * @generated
     */
    EClass PATH = eINSTANCE.getPath();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH__NODES = eINSTANCE.getPath_Nodes();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.NodeImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__STR = eINSTANCE.getNode_Str();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.BasicNodeImpl <em>Basic Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.BasicNodeImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getBasicNode()
     * @generated
     */
    EClass BASIC_NODE = eINSTANCE.getBasicNode();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.ArrayNodeImpl <em>Array Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.ArrayNodeImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getArrayNode()
     * @generated
     */
    EClass ARRAY_NODE = eINSTANCE.getArrayNode();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_NODE__FILTER = eINSTANCE.getArrayNode_Filter();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.FilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.AllFilterImpl <em>All Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.AllFilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getAllFilter()
     * @generated
     */
    EClass ALL_FILTER = eINSTANCE.getAllFilter();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.PathFilterImpl <em>Path Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.PathFilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getPathFilter()
     * @generated
     */
    EClass PATH_FILTER = eINSTANCE.getPathFilter();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_FILTER__PATH = eINSTANCE.getPathFilter_Path();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.EqualFilterImpl <em>Equal Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.EqualFilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getEqualFilter()
     * @generated
     */
    EClass EQUAL_FILTER = eINSTANCE.getEqualFilter();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL_FILTER__VALUE = eINSTANCE.getEqualFilter_Value();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.ExistFilterImpl <em>Exist Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.ExistFilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getExistFilter()
     * @generated
     */
    EClass EXIST_FILTER = eINSTANCE.getExistFilter();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.IndexFilterImpl <em>Index Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.IndexFilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getIndexFilter()
     * @generated
     */
    EClass INDEX_FILTER = eINSTANCE.getIndexFilter();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDEX_FILTER__INDEX = eINSTANCE.getIndexFilter_Index();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.BoundFilterImpl <em>Bound Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.BoundFilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getBoundFilter()
     * @generated
     */
    EClass BOUND_FILTER = eINSTANCE.getBoundFilter();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOUND_FILTER__MIN = eINSTANCE.getBoundFilter_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOUND_FILTER__MAX = eINSTANCE.getBoundFilter_Max();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.ListFilterImpl <em>List Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.ListFilterImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getListFilter()
     * @generated
     */
    EClass LIST_FILTER = eINSTANCE.getListFilter();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_FILTER__FILTER = eINSTANCE.getListFilter_Filter();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.JsonValueImpl <em>Json Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.JsonValueImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonValue()
     * @generated
     */
    EClass JSON_VALUE = eINSTANCE.getJsonValue();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.JsonNullImpl <em>Json Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.JsonNullImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonNull()
     * @generated
     */
    EClass JSON_NULL = eINSTANCE.getJsonNull();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.JsonNumberImpl <em>Json Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.JsonNumberImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonNumber()
     * @generated
     */
    EClass JSON_NUMBER = eINSTANCE.getJsonNumber();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_NUMBER__NUMBER = eINSTANCE.getJsonNumber_Number();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.JsonBooleanImpl <em>Json Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.JsonBooleanImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonBoolean()
     * @generated
     */
    EClass JSON_BOOLEAN = eINSTANCE.getJsonBoolean();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_BOOLEAN__BOOL = eINSTANCE.getJsonBoolean_Bool();

    /**
     * The meta object literal for the '{@link fr.istic.idm.swag.impl.JsonStringImpl <em>Json String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.istic.idm.swag.impl.JsonStringImpl
     * @see fr.istic.idm.swag.impl.SwagPackageImpl#getJsonString()
     * @generated
     */
    EClass JSON_STRING = eINSTANCE.getJsonString();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_STRING__VALUE = eINSTANCE.getJsonString_Value();

  }

} //SwagPackage
