/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSwagScopeProvider extends DelegatingScopeProvider {
}
