/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.parser.antlr;

import com.google.inject.Inject;
import fr.istic.idm.parser.antlr.internal.InternalSwagParser;
import fr.istic.idm.services.SwagGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SwagParser extends AbstractAntlrParser {

	@Inject
	private SwagGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSwagParser createParser(XtextTokenStream stream) {
		return new InternalSwagParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Path";
	}

	public SwagGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SwagGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
