/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SwagStandaloneSetup extends SwagStandaloneSetupGenerated {

	public static void doSetup() {
		new SwagStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
