/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag.impl;

import fr.istic.idm.swag.BasicNode;
import fr.istic.idm.swag.SwagPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BasicNodeImpl extends NodeImpl implements BasicNode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SwagPackage.Literals.BASIC_NODE;
  }

} //BasicNodeImpl
