/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.swag.impl;

import fr.istic.idm.swag.ExistFilter;
import fr.istic.idm.swag.SwagPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exist Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExistFilterImpl extends PathFilterImpl implements ExistFilter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExistFilterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SwagPackage.Literals.EXIST_FILTER;
  }

} //ExistFilterImpl
